-- Ejecuta este archivo completo en Supabase: SQL Editor > New query > Run.
-- La clave pública (anon) solo puede acceder a lo que permiten estas reglas RLS.

create table if not exists public.viajes (
  id bigint generated by default as identity primary key,
  nombre text not null check (char_length(nombre) between 1 and 80),
  apellidos text check (char_length(apellidos) <= 120),
  centro text not null check (char_length(centro) between 1 and 120),
  inicio_curso date not null,
  fin_curso date not null check (fin_curso >= inicio_curso),
  ciudad_salida text check (char_length(ciudad_salida) <= 100),
  aeropuerto text check (char_length(aeropuerto) <= 120),
  fecha_salida date,
  llegada_centro date,
  salida_centro date,
  comentarios text check (char_length(comentarios) <= 800),
  consentimiento boolean not null default false,
  telefono text check (char_length(telefono) <= 40),
  email text check (char_length(email) <= 254),
  created_at timestamptz not null default now(),
  constraint contact_requires_consent check (consentimiento or (telefono is null and email is null))
);

create index if not exists viajes_curso_idx on public.viajes (inicio_curso, fin_curso, centro);
alter table public.viajes enable row level security;

-- Lectura pública: los datos de contacto se entregan al navegador, pero no se muestran
-- hasta que se pulsa el botón y solo si existe consentimiento. Para privacidad reforzada
-- en una fase futura, usar una función RPC que no devuelva contacto por defecto.
create policy "Viajes visibles públicamente" on public.viajes for select using (true);
create policy "Cualquiera puede proponer un viaje" on public.viajes for insert with check (true);

-- No se permite editar ni borrar desde la página pública.
